[package]
name = "mora-bin"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
crossterm.workspace = true
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
serana-tree-sitter = { path = "../crates/serana-tree-sitter" }
mora-lisp = { path = "../crates/mora-lisp" }
mora-compile = { path = "../crates/mora-compile" }
mishell-parser = { path = "../crates/mishell-parser" }
display-protocol = { path = "../crates/display-protocol", features = ["tui"] }
tokio.workspace = true
thiserror.workspace = true
hostname = "0.4"
wgpu.workspace = true
winit = { workspace = true, features = ["rwh_06"] }
cosmic-text.workspace = true
glyphon.workspace = true
pollster.workspace = true
bytemuck.workspace = true
rayon.workspace = true

[dev-dependencies]
tempfile = "3.12"

[[bin]]
name = "mora"
path = "src/bin/mora.rs"

[[bin]]
name = "mora-server"
path = "src/bin/mora_server.rs"

[[bin]]
name = "mora-client"
path = "src/bin/mora_client.rs"

[[bin]]
name = "mishell"
path = "src/bin/mishell.rs"
