#[derive(Debug)]
pub struct BoxChars {
    pub top_left: &'static str,
    pub top_right: &'static str,
    pub bottom_left: &'static str,
    pub bottom_right: &'static str,
    pub horizontal: &'static str,
    pub vertical: &'static str,
    pub cross: &'static str,
    pub tee_down: &'static str,
    pub tee_up: &'static str,
    pub tee_right: &'static str,
    pub tee_left: &'static str,
}

#[derive(Debug)]
pub struct Symbols {
    pub success: &'static str,
    pub error: &'static str,
    pub warning: &'static str,
    pub info: &'static str,
    pub pending: &'static str,
    pub running: &'static str,
    pub spinner: &'static [&'static str],
    pub cursor: &'static str,
    pub expand: &'static str,
    pub collapse: &'static str,
    pub box_round: BoxChars,
    pub box_sharp: BoxChars,
    pub sep_thin: &'static str,
    pub sep_pipe: &'static str,
    pub sep_dot: &'static str,
    pub sep_slash: &'static str,
    pub checkbox_checked: &'static str,
    pub checkbox_unchecked: &'static str,
    pub checkbox_in_progress: &'static str,
    pub checkbox_abandoned: &'static str,
    pub bullet: &'static str,
    pub arrow: &'static str,
    pub hr_char: &'static str,
    pub quote_border: &'static str,
}

static UNICODE_SPINNER: &[&str] = &["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
static ASCII_SPINNER: &[&str] = &["-", "\\", "|", "/"];

pub static UNICODE: Symbols = Symbols {
    success: "✔",
    error: "✘",
    warning: "⚠",
    info: "ⓘ",
    pending: "○",
    running: "●",
    spinner: UNICODE_SPINNER,
    cursor: "❯",
    expand: "▸",
    collapse: "▾",
    box_round: BoxChars {
        top_left: "╭",
        top_right: "╮",
        bottom_left: "╰",
        bottom_right: "╯",
        horizontal: "─",
        vertical: "│",
        cross: "┼",
        tee_down: "┬",
        tee_up: "┴",
        tee_right: "├",
        tee_left: "┤",
    },
    box_sharp: BoxChars {
        top_left: "┌",
        top_right: "┐",
        bottom_left: "└",
        bottom_right: "┘",
        horizontal: "─",
        vertical: "│",
        cross: "┼",
        tee_down: "┬",
        tee_up: "┴",
        tee_right: "├",
        tee_left: "┤",
    },
    sep_thin: "┆",
    sep_pipe: "│",
    sep_dot: "·",
    sep_slash: "/",
    checkbox_checked: "✓",
    checkbox_unchecked: "○",
    checkbox_in_progress: "◌",
    checkbox_abandoned: "✗",
    bullet: "•",
    arrow: "→",
    hr_char: "─",
    quote_border: "▏",
};

pub static ASCII: Symbols = Symbols {
    success: "[ok]",
    error: "[!!]",
    warning: "[!]",
    info: "[i]",
    pending: "o",
    running: "*",
    spinner: ASCII_SPINNER,
    cursor: ">",
    expand: "+",
    collapse: "-",
    box_round: BoxChars {
        top_left: "+",
        top_right: "+",
        bottom_left: "+",
        bottom_right: "+",
        horizontal: "-",
        vertical: "|",
        cross: "+",
        tee_down: "+",
        tee_up: "+",
        tee_right: "+",
        tee_left: "+",
    },
    box_sharp: BoxChars {
        top_left: "+",
        top_right: "+",
        bottom_left: "+",
        bottom_right: "+",
        horizontal: "-",
        vertical: "|",
        cross: "+",
        tee_down: "+",
        tee_up: "+",
        tee_right: "+",
        tee_left: "+",
    },
    sep_thin: "|",
    sep_pipe: "|",
    sep_dot: "-",
    sep_slash: "/",
    checkbox_checked: "[x]",
    checkbox_unchecked: "[ ]",
    checkbox_in_progress: "[-]",
    checkbox_abandoned: "[~]",
    bullet: "*",
    arrow: "->",
    hr_char: "-",
    quote_border: "|",
};
